name = "AtlasRobot"
uuid = "436ed74b-f7b6-57fe-bd82-efdbd6c0ab0c"
repo = "https://github.com/tkoolen/AtlasRobot.jl.git"
version = "0.4.0"

[deps]
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
RigidBodyDynamics = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
